### ISSUE TITLE
Adding Node will no longer working

### ISSUE THREAD

**Issue by jamesli2021** [corbado/example-passkeys-astro#4]
If we add `npx astro add node`, the build process `npx astro build && npx astro preview` will fail to load `corbadoSetup.js` becase it is placed outside the src folder.

I'm assume that placing the source files outside src is a bad practice as `.env` is on the same path as well.

**Comment by AmalADDAD98** [comment]
@vincentdelitz I investigated the issue reported. I refactored the whole implementation in the `2-fix-issues` branch to avoid using the `corbadoSetup.js` file outside of the `src` directory. I ran the `npx astro build` and `npx astro preview` commands on the `main` branch and everything is working as expected. The build is passed and the `dist` folder is created, also the app is running .

![image](https://github.com/user-attachments/assets/450f0bab-07bf-445d-a360-86f05e15012a)

**Comment by jamesli2021** [comment]
Oh, thanks! I have adopted the new technique, and it works!
